//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumoWCF.ProductosServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductosServices.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Calculadora", ReplyAction="http://tempuri.org/IService1/CalculadoraResponse")]
        int Calculadora(int a, int b, string operacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Calculadora", ReplyAction="http://tempuri.org/IService1/CalculadoraResponse")]
        System.Threading.Tasks.Task<int> CalculadoraAsync(int a, int b, string operacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarProducto", ReplyAction="http://tempuri.org/IService1/AgregarProductoResponse")]
        string AgregarProducto(int id, string nombre, double precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarProducto", ReplyAction="http://tempuri.org/IService1/AgregarProductoResponse")]
        System.Threading.Tasks.Task<string> AgregarProductoAsync(int id, string nombre, double precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerProductosConcatenado", ReplyAction="http://tempuri.org/IService1/ObtenerProductosConcatenadoResponse")]
        string ObtenerProductosConcatenado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerProductosConcatenado", ReplyAction="http://tempuri.org/IService1/ObtenerProductosConcatenadoResponse")]
        System.Threading.Tasks.Task<string> ObtenerProductosConcatenadoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsumoWCF.ProductosServices.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsumoWCF.ProductosServices.IService1>, ConsumoWCF.ProductosServices.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Calculadora(int a, int b, string operacion) {
            return base.Channel.Calculadora(a, b, operacion);
        }
        
        public System.Threading.Tasks.Task<int> CalculadoraAsync(int a, int b, string operacion) {
            return base.Channel.CalculadoraAsync(a, b, operacion);
        }
        
        public string AgregarProducto(int id, string nombre, double precio) {
            return base.Channel.AgregarProducto(id, nombre, precio);
        }
        
        public System.Threading.Tasks.Task<string> AgregarProductoAsync(int id, string nombre, double precio) {
            return base.Channel.AgregarProductoAsync(id, nombre, precio);
        }
        
        public string ObtenerProductosConcatenado() {
            return base.Channel.ObtenerProductosConcatenado();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerProductosConcatenadoAsync() {
            return base.Channel.ObtenerProductosConcatenadoAsync();
        }
    }
}
